### ISSUE TITLE
有关于flavor方法中config.xml的问题

### ISSUE THREAD

**Issue by nickming** [hshaoGitHub/Android-Customization-Demo#1]
请问如果采用flavor方法，那么featureConfig可以通过继承的方式来实现差异化，那么每个flavor下面的config.xml自定义的话，也是自动继承的main里面的config.xml吗，还是说需要在每个config.xml里面声明各自的配置？可能问题有点简单，望解答。

**Comment by hshaoGitHub** [comment]
当然可以，config作为资源使用，可以继承main的配置，产品里只需放定制的配置

**Comment by nickming** [comment]
ok，谢谢
